"""Merge the per-scene manifest fragments into src/generated/props.ts.

    python3 assets/blender/manifest.py

Runs outside Blender: each `build.py` invocation is its own process with its own
scene, so no single Blender run knows about every prop. Each writes a fragment
to `_manifest/`, and this merges them.

The point of the generated file is that a slug is a *type*. Renaming a prop in
Blender then fails `tsc` at the call site instead of 404ing in the browser,
which is the same class of silent desync src/CLAUDE.md warns about for
viewpoints.json.
"""

import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.abspath(os.path.join(HERE, "..", ".."))
FRAGMENTS = os.path.join(HERE, "_manifest")
OUT = os.path.join(ROOT, "src", "generated", "props.ts")

HEADER = """// GENERATED by `npm run models` from assets/blender/. Do not edit.
//
// Import prop urls from here rather than writing '/models/props/<name>.glb' by
// hand: a renamed or deleted prop then breaks the build instead of failing
// silently at runtime.
"""


def main():
    fragments = sorted(glob.glob(os.path.join(FRAGMENTS, "*.json")))
    if not fragments:
        sys.exit(f"no manifest fragments in {FRAGMENTS} — run the Blender builds first")

    props = {}
    for path in fragments:
        with open(path) as fh:
            data = json.load(fh)
        # _manifest/ is gitignored and per-developer, so a renamed or deleted
        # scene leaves its fragment behind. Without this it keeps emitting
        # phantom slugs that tsc happily accepts.
        pkg = os.path.join(HERE, data["scene"])
        if not (os.path.isdir(pkg) or os.path.isfile(pkg + ".py")):
            print(f"  skipping stale fragment {os.path.basename(path)}: "
                  f"no {data['scene']}/ package")
            continue
        for entry in data["props"]:
            entry["scene"] = data["scene"]
            if entry["slug"] in props:
                sys.exit(f"duplicate slug {entry['slug']!r} across scenes")
            props[entry["slug"]] = entry

    slugs = sorted(props)
    if not slugs:
        sys.exit("no props in any fragment — refusing to write an empty manifest")
    lines = [HEADER]
    lines.append("export type PropSlug =")
    lines += [f"  | '{slug}'" for slug in slugs]
    lines[-1] += "\n"

    lines.append("""export interface PropEntry {
  slug: PropSlug
  /** Path under public/, ready for useGLTF. */
  url: string
  /** Triangles in the evaluated mesh, modifiers applied. */
  tris: number
  /** Size of the exported .glb on disk. */
  bytes: number
  /** Bounding size in metres, three.js axes: [x, y, z]. */
  size: readonly [number, number, number]
  /** Blender scene package that builds it. */
  scene: string
}

export const PROPS = {""")

    for slug in slugs:
        e = props[slug]
        size = ", ".join(f"{v}" for v in e["size"])
        lines.append(f"""  '{slug}': {{
    slug: '{slug}',
    url: '/models/props/{slug}.glb',
    tris: {e["tris"]},
    bytes: {e["bytes"]},
    size: [{size}],
    scene: '{e["scene"]}',
  }},""")

    lines.append("""} as const satisfies Record<PropSlug, PropEntry>

/** Every prop slug, sorted. Useful for preloading and for budget tests. */
export const PROP_SLUGS = Object.keys(PROPS) as PropSlug[]

export const propUrl = (slug: PropSlug): string => PROPS[slug].url
""")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as fh:
        fh.write("\n".join(lines))

    total = sum(e["bytes"] for e in props.values())
    print(f"manifest: {len(slugs)} props, {total / 1024:.0f}KB total -> {OUT}")


if __name__ == "__main__":
    main()
